kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: hicoin-clientmanager-webapi
  name: hicoin-clientmanager-webapi
  namespace: default
spec:   
  ports:
    - name: http
      port: 5001
      targetPort: 5001
  selector:
    k8s-app: hicoin-clientmanager-webapi
